version: "3.9"

services:
  db:
    image: postgres:16
    container_name: optitrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: optitrack_db
      POSTGRES_USER: optitrack_user
      POSTGRES_PASSWORD: optitrack_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
